### ISSUE TITLE
How should the data of the received video be processed after the SIP protocol is interoperable, so that livekit can be forwarded to other participants?

### ISSUE THREAD

**Issue by sunnytzh** [livekit/sip#205] opened 2024-10-17 09:32 UTC
1.Interfacing with third-party platforms through the SIP protocol: After establishing UDP communication after expanding the SDP information of video, what processing should be performed on the received video data (whether it needs to be decoded, what format it needs to be decoded into, and then whether it needs to be re-encoded into a specific format), and which interfaces can be successfully forwarded to other video conference participants.
      2.How to process the real-time video data of others in the video conference on the livekit side, how to synthesize a picture during processing, and then how to process the synthesized video data, which can be encapsulated into RTP data packets and sent to the peer.

Thankyou!

**Comment by dennwc** [comment] 2024-10-17 13:25
As you may know LiveKit SIP doesn't support video at the moment, as was discussed in https://github.com/livekit/sip/issues/192. Please post these question to the relevant issues instead of creating new ones. Thank you.

I will update https://github.com/livekit/sip/issues/24 to list current blockers.

Closing as duplicate of #192

**Closed by dennwc** 2024-10-17 13:25 UTC
Labels: question
