### ISSUE TITLE
How to handle and forward new video data in SIP interface? 

### ISSUE THREAD

**Issue by sunnytzh** [livekit/sip#192] opened 2024-10-08 06:21 UTC
At present, we can only choose SIP to connect the third-party platform, now want to add Video part of the processing, how should be handled to complete this part of the work, at present we consider the following parts need to be handled: 
    1. Description of the new video section in the SDP Information 
    2. Handling of the new video port when opening the Port 
    3. How to handle the new video port when it receives the video data sent to the other end to be forwarded to other participants 
    4. How to forward video data from other participants in the video conference to third-party platforms through the video port 
    5. ...
Please help us to assess whether there is a solution to these problems that can be used for reference, or what problems are not taken into account, and how these problems should be implemented, online and so on. Thank you.

**Comment by davidzhao** [comment] 2024-10-08 06:46
dupe of #24, re-opened that issue to keep track of the request

**Closed by davidzhao** 2024-10-08 06:46 UTC

**Comment by sunnytzh** [comment] 2024-10-08 07:00
I saw the comment on #24, but I don't feel organized and clear enough. The answer is a little messy. Can you sort out the details clearly? Thank you.

**Comment by sunnytzh** [comment] 2024-10-08 07:07
We do have this scenario at the moment, and we see it happening to many SIP users as well. The scenarios that illustrate these are becoming more and more extensive in practice, and we hope that the needs of this scenario will be addressed. Or give us guidance on the implementation of the technical ideas, we follow your recommended ideas to achieve, we hope to share our successful solutions to continue to expand the application capabilities of livekit. Thank you.
