### ISSUE TITLE
SIP Codec

### ISSUE THREAD

**Issue by cmurrayis** [livekit/sip#122] opened 2024-07-15 05:48 UTC
Appears there is no way to set the CODECs for the calls via LiveKit-SIP as we're seeing audio issues with audio unaudible.

Attached is a example recording and the packet snippets.
![image (5)](https://github.com/user-attachments/assets/c6847007-0122-48bb-904b-aed4ee3431ab)
![image (4)](https://github.com/user-attachments/assets/d45dfd04-10eb-40f6-abe7-1ad2038d01ea)
![image (3)](https://github.com/user-attachments/assets/4199fa99-0cc1-4da9-be70-b5e9a79bcba8)
![image (2)](https://github.com/user-attachments/assets/92cccba0-ee6d-41d2-95b4-2de69769db38)
![image (1)](https://github.com/user-attachments/assets/8368b365-9a9c-46fd-a89a-d0f801d1b22d)

Audio Sample: [https://www.dropbox.com/scl/fi/yxwtkp9769l8fkdpqdzle/Recording-3.wav?rlkey=iwcrpvse8h1qhi3nefmaspl0y&st=67k4orq4&dl=0](url)

**Comment by dennwc** [comment] 2024-07-15 12:03
@cmurrayis What version of LiveKit SIP are you using? This was definitely a problem with older versions and should be fixed in latest one. We didn't tag is as a proper release yet.

**Comment by cmurrayis** [comment] 2024-07-15 12:41
Hi @dennwc 

I’ll check the version tomorrow however it was only pulled on Friday so I’d suspect pretty recent if not the latest.

Are there any checks or logs I can gather at the same time and come back to you with all the details at once?

**Comment by dennwc** [comment] 2024-07-15 12:53
In general the version is indeed the latest (from Git), then PCAP dump would be appreciated, so that I can model the same case locally.

But since you said "pulled", I assume it's from DockerHub, which only tracks tagged releases for now. I'll update the CI to push a `dev` tag as well. If you could build the Docker image locally and test it - that would be great too.

**Comment by cmurrayis** [comment] 2024-07-15 13:48
Hi,

How can I get the pcap to you securely?

**Comment by dennwc** [comment] 2024-07-15 14:43
I'll DM you on Slack :+1:

**Comment by cmurrayis** [comment] 2024-07-15 19:09
Sure

**Comment by cmurrayis** [comment] 2024-07-19 04:11
The most recent push mostly fixed the issue however I am not sure if it is a codec issue still or a gain issue but the audio back is very loud.

https://github.com/user-attachments/assets/eb87e339-5b32-462d-8548-359468ae6cb3

**Comment by dennwc** [comment] 2024-08-20 13:20
Should be fixed in the most recent version. Feel free to reopen if you could still reproduce it.

**Closed by dennwc** 2024-08-20 13:20 UTC
