### ISSUE TITLE
How to use TLS protocol for outbound

### ISSUE THREAD

**Issue by DU-718** [livekit/sip#145] opened 2024-08-19 03:36 UTC
How to specify the use of TLS protocol when creating SIP outbound relays in LiveKit CLI, which now defaults to UDP protocol.

The following image shows the contents of my outboundTrunkjson file.
![微信图片_20240819113313](https://github.com/user-attachments/assets/918b0915-a804-4aaa-834f-53e41152a6e0)

The following image shows the contents of my sipParticipantjson file.
![微信图片_20240819113443](https://github.com/user-attachments/assets/ab6e893f-b35a-4ef8-a008-d77909f57fa6)

I would greatly appreciate your assistance in answering my questions.

**Comment by dennwc** [comment] 2024-08-19 09:24
We do not support TLS for now. Duplicate of https://github.com/livekit/sip/issues/71

**Comment by dennwc** [comment] 2024-08-19 09:25
We do not support TLS for now. Duplicate of https://github.com/livekit/sip/issues/71

**Closed by dennwc** 2024-08-19 09:25 UTC
Labels: enhancement
